resume: 'models/test_Aorta24/checkpoint_epoch_400.pth' # Checkpoint path

# EVALUATION
eval_only: true
batch_size: 1
max_inference_levels: 500
max_nodes_per_level: 100
volume_eval: true
sub_volume_eval: false
test_sample: ["Aorta24_028"] # list of 'sample_id-tree_id'

# Dataset
# dataset: data/ASOCA

# Dataloader
mask: false