resume: 'models/test_ASOCA/checkpoint_epoch_1000.pth' # Checkpoint path

# EVALUATION
eval_only: true
batch_size: 1
max_inference_levels: 500
max_nodes_per_level: 100
volume_eval: true
sub_volume_eval: false
test_sample: ["Diseased_8-0"] # list of 'sample_id-tree_id'

# Dataset
# dataset: data/ASOCA

# Dataloader
mask: true