amp: true
batch_size: 4
batch_size_val: 1
bifur_prob: 0.2
cache_num: 16
cache_rate_train: 1.0
clip_max_norm: 0.1
cls_loss_coef: 1.0
custom_focal_weights_value:
- 0.33300486
- 0.32274583
- 0.33308958
- 0.01115972
data_dir: data/Aorta24
debug: false
dec_layers: 6
depths:
- 2
- 2
- 2
- 2
determinism: true
device: cuda:0
dim_feedforward: 2048
dir_loss_coef: 1.0
dist_url: env://
distributed: false
dropout: 0.1
end_prob: 0.2
epochs: 20000
eval_limit_levels: true
eval_limit_nodes_per_level: true
eval_only: false
eval_perma_finish_end_bifur: true
focus_vol_size: 32
gc_level: 1
hidden_dim: 96
lr: 0.0001
mask: false
max_inference_levels: 50
max_nodes_per_level: 500
mem_vol_ds: 2
min_lr_mltp: 0.1
n_workers_train: 2
nheads: 8
num_bifur_queries: 10
num_heads:
- 3
- 6
- 12
- 24
num_init_workers: 4
num_prev_pos: 5
num_queries: 50
num_replace_workers: 2
output_dir: models/test_Aorta24
pad_class: false
patch_size: 2
pre_norm: false
rad_loss_coef: 1.0
replace_rate: 0.125
resume: ''
root_prob: 0.1
save_checkpoint: 10
save_model_interval: 100
seed: 37
seq_len: 10
set_cost_class: 1.0
set_cost_direction: 1.0
set_cost_radius: 1.0
share_direc_embed: true
share_direc_embed_num: 6
sub_vol_size: 64
sub_volume_eval: false
take_in_between_level: false
test_sample: []
traj_train_len: 6
unetr_dim: 24
val_interval: 2000
val_interval_sv: 2000
var_traj_train_len: true
volume_eval: false
weight_decay: 0.0001
window_input: true
window_max: 1400
window_min: -400
window_size: 7
world_size: 1
